<a href="https://colab.research.google.com/github/kamilsielski-py/git/blob/master/Algebra_liniowa.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
# 1. Norma wektora, norma euklidesowa, odległość dwóch punktów na płaszczyźnie

In [3]:
import numpy as np
v1 = np.array([0, 4])

In [4]:
v1

array([0, 4])

In [6]:
np.linalg.norm(v1) # policzy odłegłość

4.0

In [7]:
# długość wektora w przestrzeni Rn

In [8]:
v2 = np.array([-10, 10, 13])
np.linalg.norm(v2)

19.209372712298546

In [9]:
# odległość dwóch punktów na płaszczyźnie

In [10]:
p = np.array([3, 0])

In [11]:
q = np.array([0, 4])

In [12]:
np.linalg.norm(p-q)

5.0

In [13]:
# odległość dwóch punktów w przestrzeni Rn

In [14]:
p = np.array([3, 0, 1])

In [15]:
q = np.array([0, 4, 2])

In [16]:
np.linalg.norm(p-q)

5.0990195135927845

In [17]:
# Mnożenie macierzy

In [20]:
# Aby móc pomnożyć dwie macierze liczba kolumn w lewej macierzy musi się zgadzać z liczbą wierszy w prawej macierzy.
# Mnożenie macierzy nie jest przemienne


In [25]:
X = np.array([[2, -1, 3],
              [3, 1, 0]])

Y = np.array([[2, 1, -1],
              [0, -1, 2],
              [3, 2, 0]])

In [26]:
print(X, '\n')
print(Y)

[[ 2 -1  3]
 [ 3  1  0]] 

[[ 2  1 -1]
 [ 0 -1  2]
 [ 3  2  0]]


In [27]:
np.dot( X, Y)

array([[13,  9, -4],
       [ 6,  2, -1]])

In [30]:
### WYZNACZNIK MACIERZ JEDNOSTKOWA< ODWROTNA i TRANSPONOWANA

In [31]:
A = np.array([[2, 4], [-1, 3]])

In [32]:
np.linalg.det(A) # wyznacznik macierzy

9.999999999999998

In [33]:
# Ślad macierzy

In [34]:
np.trace(A)

5

In [35]:
# Macierz jednostkowa, współczynniki na przekątnej są równe 1


In [36]:
np.eye(5, dtype='int') # domyślnie jest float

array([[1, 0, 0, 0, 0],
       [0, 1, 0, 0, 0],
       [0, 0, 1, 0, 0],
       [0, 0, 0, 1, 0],
       [0, 0, 0, 0, 1]])

In [37]:
# MAcierz odwrotna, tylko do macierzy kwadratowej


In [38]:
B = np.linalg.inv(A)

In [39]:
B


array([[ 0.3, -0.4],
       [ 0.1,  0.2]])

In [40]:
np.dot(A, B)

array([[1.00000000e+00, 0.00000000e+00],
       [2.77555756e-17, 1.00000000e+00]])

In [41]:
# Macierz Transponowana

In [42]:
np.transpose(A)

array([[ 2, -1],
       [ 4,  3]])

In [43]:
B.T

array([[ 0.3,  0.1],
       [-0.4,  0.2]])

### UKŁAD RÓWNAŃ

In [44]:
""" 2x + 4y = 10
    x - y = -1 """
    

' 2x + 4y = 10\n    x - y = -1 '

In [45]:
'x = 1, y = 2 '

'x = 1, y = 2 '

In [48]:
A = np.array([[2, 4], [1, -1]]) # macierz współczynników
A

array([[ 2,  4],
       [ 1, -1]])

In [50]:
B = np.array([[10], [-1]]) # wektor wyrazów wolnych

In [51]:
A_inv = np.linalg.inv(A)

In [52]:
X = np.dot(A_inv, B)
X

array([[1.],
       [2.]])