<a href="https://colab.research.google.com/github/kamilsielski-py/git/blob/master/Numpy_.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import numpy as np

In [ ]:
np.__version__

'1.18.5'

In [ ]:
print(dir(np))

In [ ]:
help(np.array)

In [ ]:
# Podstawowym obiektem numpy jest wielowymiarowa tablica.


In [ ]:
x = np.array([1, 3])

In [ ]:
x

array([1, 3])

In [ ]:
x.ndim # wymiar tablicy

1

In [ ]:
x.shape # kształt

(2,)

In [ ]:
x.size # liczba elementów w tablicy

2

In [ ]:
x.dtype

dtype('int64')

In [ ]:
x = np.array([1.3, 2.3, 3.3])
print(x)

[1.3 2.3 3.3]


## Dwuwymiarowe tablice


In [ ]:
x = np.array([[1,2], [-3, 1]])

In [ ]:
x


array([[ 1,  2],
       [-3,  1]])

In [5]:
np.zeros(shape=(4,10))

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [7]:
np.ones(shape=(5,5), dtype=int)

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [11]:
np.full(shape=(3,3), fill_value=4, dtype='int')

array([[4, 4, 4],
       [4, 4, 4],
       [4, 4, 4]])

In [12]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [13]:
np.arange(start=5, stop=10)

array([5, 6, 7, 8, 9])

In [14]:
np.arange(start=5, step=5, stop=20)

array([ 5, 10, 15])

In [15]:
np.linspace(start=0, stop=1, num=5)

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [16]:
# Zmienianie kształtu danych


In [17]:
A = np.arange(15)

In [18]:
A.reshape((3,5))

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [19]:
# wstawiając -1 python sam dobierze odpowiednią liczbę parametrów


### PODSTAWOWE OPERACJE NA TABLICACH

In [20]:
A = np.array([3, 1, 4, 2])

In [21]:
B = np.array([3, -1, 3, 2])

In [22]:
print(A)

[3 1 4 2]


In [23]:
print(B)

[ 3 -1  3  2]


In [24]:
A + B # dodawanie element o elemencie

array([6, 0, 7, 4])

In [25]:
A - B

array([0, 2, 1, 0])

In [26]:
A / B # tablice nie mogą zawierać zer

array([ 1.        , -1.        ,  1.33333333,  1.        ])

In [27]:
# Metody do wykonywania działań

In [28]:
np.add(A,B)

array([6, 0, 7, 4])

In [29]:
np.subtract(A,B
            )

array([0, 2, 1, 0])

In [30]:
np.multiply(A,B)

array([ 9, -1, 12,  4])

In [31]:
np.divide(A,B)

array([ 1.        , -1.        ,  1.33333333,  1.        ])

In [32]:
# Mnożenie macierzowe

In [33]:
X = np.array([[1,3],[-2,0]])

In [35]:
Y = np.array([[6,0], [-1,2]])

In [36]:
np.dot(X, Y)

array([[  3,   6],
       [-12,   0]])

In [37]:
X.dot(Y)

array([[  3,   6],
       [-12,   0]])

In [38]:
Y.dot(X)

array([[ 6, 18],
       [-5, -3]])

In [39]:
X @ Y # to też mnożenie macierzowe, mnożenie macierzy nie jest działaniem przemiennym

array([[  3,   6],
       [-12,   0]])

In [41]:
### Generowanie liczb pseudolosowych

In [44]:
np.random.seed(0)


In [45]:
np.random.randn()

1.764052345967664

In [46]:
np.random.randn(10)

array([ 0.40015721,  0.97873798,  2.2408932 ,  1.86755799, -0.97727788,
        0.95008842, -0.15135721, -0.10321885,  0.4105985 ,  0.14404357])

In [47]:
np.random.randn(10, 4)

array([[ 1.45427351,  0.76103773,  0.12167502,  0.44386323],
       [ 0.33367433,  1.49407907, -0.20515826,  0.3130677 ],
       [-0.85409574, -2.55298982,  0.6536186 ,  0.8644362 ],
       [-0.74216502,  2.26975462, -1.45436567,  0.04575852],
       [-0.18718385,  1.53277921,  1.46935877,  0.15494743],
       [ 0.37816252, -0.88778575, -1.98079647, -0.34791215],
       [ 0.15634897,  1.23029068,  1.20237985, -0.38732682],
       [-0.30230275, -1.04855297, -1.42001794, -1.70627019],
       [ 1.9507754 , -0.50965218, -0.4380743 , -1.25279536],
       [ 0.77749036, -1.61389785, -0.21274028, -0.89546656]])

In [49]:
np.random.rand() # wartość losowa z przedziału 0-1

0.3687251706609641

In [50]:
np.random.rand(10, 2)

array([[0.82099323, 0.09710128],
       [0.83794491, 0.09609841],
       [0.97645947, 0.4686512 ],
       [0.97676109, 0.60484552],
       [0.73926358, 0.03918779],
       [0.28280696, 0.12019656],
       [0.2961402 , 0.11872772],
       [0.31798318, 0.41426299],
       [0.0641475 , 0.69247212],
       [0.56660145, 0.26538949]])

In [52]:
np.random.randint(10) # wartość losowa

9

In [53]:
np.random.randint(low=10, high=100, size=5)

array([68, 75, 46, 20, 96])

In [55]:
np.random.choice([4, 2, 1, 3, 5])

4

In [56]:
data = np.arange(10)

In [57]:
data

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [58]:
np.random.shuffle(data)

In [59]:
data

array([5, 1, 4, 9, 8, 6, 7, 0, 3, 2])

### PODSTAWOWE FUNKCJE

In [60]:
np.exp(1)

2.718281828459045

In [61]:
np.sqrt(4)

2.0

In [62]:
np.all([2, 3, 1]) # zwraca wartość logiczną, każda musi mieć TRUE żeby zwróciłą true

True

In [63]:
np.any([1, 2, 3]) # spr czy jakikolwiek obiekt jest prawdą

True

In [66]:
A = np.random.rand(5)

In [67]:
A

array([0.57225191, 0.22308163, 0.95274901, 0.44712538, 0.84640867])

In [68]:
np.argmax(A) # zwróci indeks wartości największej

2

In [69]:
A[np.argmax(A)]

0.952749011516985

In [70]:
np.argmin(A)

1

In [71]:
np.argsort(A) # sortowanie indeksami

array([1, 3, 0, 4, 2])

In [72]:
np.max(A)

0.952749011516985

In [73]:
np.min(A)

0.2230816326406183

In [74]:
np.mean(A)

0.6083233202074464

In [75]:
np.median(A)

0.5722519057908734

In [76]:
np.std(A)

0.26495689194535754

In [77]:
A = np.arange(20)

In [78]:
A


array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [79]:
A[1]

1

In [80]:
A[1:2]

array([1])

In [81]:
A[:3]

array([0, 1, 2])

In [83]:
A = A.reshape(4, 5)

In [84]:
A

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [85]:
A[0]

array([0, 1, 2, 3, 4])

In [87]:
A[:,0] # pierwsza kolumna

array([ 0,  5, 10, 15])

In [89]:
A[:, -1]

array([ 4,  9, 14, 19])

In [90]:
A[1, 2]

7

In [91]:
# Przypisanie nowych wartości do naszej tablicy

In [92]:
A[1, 2] = 14
A

array([[ 0,  1,  2,  3,  4],
       [ 5,  6, 14,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

### ITERACJA PO TABLICACH, ZMIANA ROZMIARU ORAZ MASKI LOGICZNE

In [93]:
for row in A:
  print(row)

[0 1 2 3 4]
[ 5  6 14  8  9]
[10 11 12 13 14]
[15 16 17 18 19]


In [99]:
for item in A.flat:
  print(item)

0
1
2
3
4
5
6
14
8
9
10
11
12
13
14
15
16
17
18
19


In [100]:
# Zmiana rozmiaru tablic

In [101]:
A
A.shape

(4, 5)

In [102]:
A.reshape(5, 4)

array([[ 0,  1,  2,  3],
       [ 4,  5,  6, 14],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19]])

In [103]:
A.ravel() # operacja odwrotna do operacji reshape, wypłaszcza dane do postaci jednowymiarowej

array([ 0,  1,  2,  3,  4,  5,  6, 14,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [105]:
A.T # zamiana kolumn na wiersze

array([[ 0,  5, 10, 15],
       [ 1,  6, 11, 16],
       [ 2, 14, 12, 17],
       [ 3,  8, 13, 18],
       [ 4,  9, 14, 19]])

## MASKI LOGICZNE

In [107]:
A = np.arange(start=-10, stop=10, step=0.5)

In [108]:
A = A.reshape(10, -1)

In [109]:
A

array([[-10. ,  -9.5,  -9. ,  -8.5],
       [ -8. ,  -7.5,  -7. ,  -6.5],
       [ -6. ,  -5.5,  -5. ,  -4.5],
       [ -4. ,  -3.5,  -3. ,  -2.5],
       [ -2. ,  -1.5,  -1. ,  -0.5],
       [  0. ,   0.5,   1. ,   1.5],
       [  2. ,   2.5,   3. ,   3.5],
       [  4. ,   4.5,   5. ,   5.5],
       [  6. ,   6.5,   7. ,   7.5],
       [  8. ,   8.5,   9. ,   9.5]])

In [110]:
A > 0 # wartości większe od zera

array([[False, False, False, False],
       [False, False, False, False],
       [False, False, False, False],
       [False, False, False, False],
       [False, False, False, False],
       [False,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True]])

In [111]:
A[A > 0]

array([0.5, 1. , 1.5, 2. , 2.5, 3. , 3.5, 4. , 4.5, 5. , 5.5, 6. , 6.5,
       7. , 7.5, 8. , 8.5, 9. , 9.5])

In [112]:
np.bitwise_and(A > -5, A < 5)

array([[False, False, False, False],
       [False, False, False, False],
       [False, False, False,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True, False, False],
       [False, False, False, False],
       [False, False, False, False]])

In [113]:
A[np.bitwise_and(A > -5, A < 5)]

array([-4.5, -4. , -3.5, -3. , -2.5, -2. , -1.5, -1. , -0.5,  0. ,  0.5,
        1. ,  1.5,  2. ,  2.5,  3. ,  3.5,  4. ,  4.5])

In [114]:
np.bitwise_or(A < -5, A > 5)

array([[ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True, False, False],
       [False, False, False, False],
       [False, False, False, False],
       [False, False, False, False],
       [False, False, False, False],
       [False, False, False,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True]])

In [115]:
A[np.bitwise_or(A < -5, A > 5)]

array([-10. ,  -9.5,  -9. ,  -8.5,  -8. ,  -7.5,  -7. ,  -6.5,  -6. ,
        -5.5,   5.5,   6. ,   6.5,   7. ,   7.5,   8. ,   8.5,   9. ,
         9.5])