<a href="https://colab.research.google.com/github/kamilsielski-py/git/blob/master/Numpy_.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import numpy as np

In [ ]:
np.__version__

'1.18.5'

In [ ]:
print(dir(np))

In [ ]:
help(np.array)

In [ ]:
# Podstawowym obiektem numpy jest wielowymiarowa tablica.


In [ ]:
x = np.array([1, 3])

In [ ]:
x

array([1, 3])

In [ ]:
x.ndim # wymiar tablicy

1

In [ ]:
x.shape # kształt

(2,)

In [ ]:
x.size # liczba elementów w tablicy

2

In [ ]:
x.dtype

dtype('int64')

In [ ]:
x = np.array([1.3, 2.3, 3.3])
print(x)

[1.3 2.3 3.3]


## Dwuwymiarowe tablice


In [ ]:
x = np.array([[1,2], [-3, 1]])

In [ ]:
x


array([[ 1,  2],
       [-3,  1]])

In [5]:
np.zeros(shape=(4,10))

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [7]:
np.ones(shape=(5,5), dtype=int)

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [11]:
np.full(shape=(3,3), fill_value=4, dtype='int')

array([[4, 4, 4],
       [4, 4, 4],
       [4, 4, 4]])

In [12]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [13]:
np.arange(start=5, stop=10)

array([5, 6, 7, 8, 9])

In [14]:
np.arange(start=5, step=5, stop=20)

array([ 5, 10, 15])

In [15]:
np.linspace(start=0, stop=1, num=5)

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [16]:
# Zmienianie kształtu danych


In [17]:
A = np.arange(15)

In [18]:
A.reshape((3,5))

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [19]:
# wstawiając -1 python sam dobierze odpowiednią liczbę parametrów


### PODSTAWOWE OPERACJE NA TABLICACH